### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by zunpiau** [iAcn/MBEStyle#3]
`申请` 页面下拉刷新时必定闪退
系统：AospExtended 7.1.1
````
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
	at android.support.v7.widget.ak.v(Unknown Source)
	at android.support.v7.widget.ak.a(Unknown Source)
	at android.support.v7.widget.bf.a(Unknown Source)
	at android.support.v7.widget.RecyclerView.a(Unknown Source)
	at android.support.v7.widget.RecyclerView.N(Unknown Source)
	at android.support.v7.widget.RecyclerView.p(Unknown Source)
	at android.support.v7.widget.RecyclerView.c(Unknown Source)
	at android.support.v7.widget.RecyclerView$1.run(Unknown Source)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	...
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/me.iacn.mbestyle-1/base.apk"],nativeLibraryDirectories=[/data/app/me.iacn.mbestyle-1/lib/arm, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
````

**Comment by meolunr** [comment]
感谢反馈！我今晚看一下 (๑>؂<๑）

**Comment by meolunr** [comment]
已经修复，感谢 ( • ̀ω•́ )✧
