### ISSUE TITLE
在 MIUI 9 上退出应用时崩溃

### ISSUE THREAD

**Issue by seasonyuu** [iAcn/MBEStyle#5]
java.lang.RuntimeException: Unable to destroy activity {me.iacn.mbestyle/me.iacn.mbestyle.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void a.a.b.b.dispose()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4265)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4283)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6315)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void a.a.b.b.dispose()' on a null object reference
	at me.iacn.mbestyle.ui.c.f.h(Unknown Source)
	at me.iacn.mbestyle.ui.c.d.onDestroyView(Unknown Source)
	at android.app.Fragment.performDestroyView(Fragment.java:2570)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
	at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2069)
	at android.app.FragmentController.dispatchDestroy(FragmentController.java:242)
	at android.app.Activity.performDestroy(Activity.java:7057)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4252)
	... 9 more

**Comment by seasonyuu** [comment]
看起来会混淆过…大概我也给不了什么意见。


机型：一加3T
ROM：MIUI 9 base on Android 7.0

**Comment by meolunr** [comment]
感谢反馈，本地已修复，暂未 Push
